services:
  fastapi:
    image: ssngam/fastapi:dev
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000
  streamlit:
    image: ssngam/streamlit:dev
    build:
      context: ./streamlit_app
      dockerfile: dockerfile
    ports:
      - 8501:8501
    environment:
      API_URL: http://fastapi:8000